; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "All2KeyIME"
!define COMPANY_NAME "CallAnswer"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define RELVERSION      "0.1.2"
!define APPNAME         "All2key ${RELVERSION}"

; MUI 1.67 compatible ------
;!include "x64.nsh"
;!include "MUI2.nsh"
;!include "Sections.nsh"

!include "MUI.nsh"




!define DLLNAME "all2keyIME.dll"
!define X64SRC "..\x64\Release\${DLLNAME}"
;!define X86SRC "..\cpp\Win32\Release\${DLLNAME}"
!define DATSRC ".\Dictionary\dict.txt"
!define INSTDIR "${COMPANY_NAME}\All2keyIME"

!define NAVILIME_ICON ".\a2kime.ico"
!define NAVILIME_CTRL_TOOL "..\navilIME_control\navilIME_control\bin\Release\navilIME_control.exe"



;--------------------
; Configuration 

  Name "${APPNAME}"
  OutFile "All2KeyIME-${RELVERSION}.exe"



;-----------------
; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"


; Pages 
  !insertmacro MUI_DEFAULT MUI_WELCOMEFINISHPAGE_BITMAP "setup.bmp"


; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE ".\license.rtf"

;History Page
!insertmacro MUI_PAGE_LICENSE ".\history.txt"


; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
;!define MUI_FINISHPAGE_RUN "$INSTDIR\${PRODUCT_NAME}.exe"
!insertmacro MUI_PAGE_FINISH
; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES
; Language files
!insertmacro MUI_LANGUAGE "Korean"

; MUI end ------

InstallDir "$PROGRAMFILES\${COMPANY_NAME}\${PRODUCT_NAME}\"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01

; 64 bit
  SetOutPath "$PROGRAMFILES64\${INSTDIR}"
  SetOverwrite ifnewer
  File "${X64SRC}"
  File "${DATSRC}"

;  File "${NAVILIME_CTRL_TOOL}"
  File "${NAVILIME_ICON}"

;  File "src\${PRODUCT_NAME}.exe"
;  File "..\cpp\x64\Release\All2KeyIME.exe"


  # Start Menu
  CreateDirectory "$SMPROGRAMS\${INSTDIR}"
  CreateShortCut "$SMPROGRAMS\${COMPANY_NAME}\Setting.lnk" "$PROGRAMFILES64\${INSTDIR}\navilIME_control.exe" "" "$PROGRAMFILES64\${INSTDIR}\a2kime.ico" 0

;------------------------------------
; 32 bit
;  SetOutPath "$PROGRAMFILES32\${INSTDIR}"
;  SetOverwrite try
;  File "${X86SRC}"
;  File "${DATSRC}"
  
  Exec 'regsvr32 "$PROGRAMFILES64\${INSTDIR}\${DLLNAME}"'
;  Exec 'regsvr32 "$PROGRAMFILES32\${INSTDIR}\${DLLNAME}"'



;  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
;  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe"
;  CreateShortCut "$DESKTOP\LSI Studio.lnk" "$INSTDIR\${PRODUCT_NAME}.exe"
;  CreateShortCut "$DESKTOP\LSI Player.lnk" "$INSTDIR\${PRODUCT_NAME}.exe" "multi_window"
  
  
  ;ExecWait "msiexec /i mariadb-10.10.1-winx64.msi ADDLOCAL=ALL REMOVE=HeidiSQL SERVICENAME=sunkwang_db PORT=3306 PASSWORD=1234 UTF8=true"
  ;ExecWait 'C:\Program Files\MariaDB 10.10\bin\mysql.exe -uroot -p1234 -e "create database sundb"';
SectionEnd


;!define LOCKDRIVER "haspdinst.exe"
!define TIMEDOT "vcredist_x86.exe"
Function .onInstSuccess
                 
    ; delete registry....
    DeleteRegKey HKCU "Software\QN Application\${PRODUCT_NAME}"
                  
                  
FunctionEnd




Section -AdditionalIcons
;  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
;  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
;  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteUnInstaller "$PROGRAMFILES64\${INSTDIR}\uninst.exe"
;  WriteUnInstaller "$PROGRAMFILES32\${INSTDIR}\uninst.exe"


;  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\${PRODUCT_NAME}.exe"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\${PRODUCT_NAME}.exe"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
;  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)는(은) 완전히 제거되었습니다. 재부팅 권장"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(^Name)을(를) 제거하시겠습니까?" IDYES +2
  Abort
FunctionEnd



Section Uninstall
  
  ;ExecWait 'msiexec.exe /i "C:\Program Files (x86)\quarternote\SMS\mariadb-10.10.1-winx64.msi" REMOVE=ALL'


  Exec 'regsvr32 -u "$PROGRAMFILES64\${INSTDIR}\${DLLNAME}"'
; old
;  Exec 'regsvr32 -u "$PROGRAMFILES32\All2keyIME\All2KeyIME.dll"'
;  Exec 'regsvr32 -u "$PROGRAMFILES64\All2keyIME\All2KeyIME.dll"'

  Exec 'taskkill /f /im ctfmon.exe'

  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\${PRODUCT_NAME}.exe"
  Delete "$INSTDIR\${PRODUCT_NAME}.dll"
  

  Delete "$SMPROGRAMS\${PRODUCT_NAME}\Uninstall.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\Website.lnk"
  Delete "$DESKTOP\${PRODUCT_NAME}.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk"
  
  Delete "$INSTDIR\uninst.exe"
  Delete "$PROGRAMFILES64\${INSTDIR}\${DLLNAME}"
  
  RMDir /r "$INSTDIR\data"
  RMDir "$SMPROGRAMS\${PRODUCT_NAME}"
  RMDir "$INSTDIR"

;  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
;  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd